language: node_js
sudo: false

script:
  - npm run travis
  - ./integration.sh $APP_PATH

node_js:
  - "0.10"
  - "0.12"
  - "iojs"

matrix:
  fast_finish: true

env:
  matrix:
    - INTEGRATION_REPO="https://github.com/discourse/discourse.git" APP_PATH="discourse/jsapp"
    - INTEGRATION_REPO="https://github.com/aptible/ember-json-schema.git" APP_PATH="ember-json-schema/app"

before_script:
  - ln -s ../ ./node_modules/jscs-ember-deprecations
  - git clone $INTEGRATION_REPO
