language: node_js
sudo: false

script: "npm run travis"

node_js:
  - "0.10"
  - "0.12"
  - "iojs"

cache:
  directories:
  - node_modules

matrix:
  fast_finish: true

before_script:
  - ln -s ../ ./node_modules/jscs-ember-deprecations
