language: node_js
sudo: false

script:
  - npm run travis
  - ./node_modules/jscs/bin/jscs --config .integration_jscsrc discourse/jsapp/

node_js:
  - "0.10"
  - "0.12"
  - "iojs"

matrix:
  fast_finish: true

before_script:
  - ln -s ../ ./node_modules/jscs-ember-deprecations
  - git clone https://github.com/discourse/discourse.git discourse
